import type { AgentSession, Automation, Schedule } from '@waku/client'

/**
 * State shown by the shared automation deletion confirmation.
 */
export type AutomationDeleteConfirmation = {
  automationId: string
  cascadeSessions: boolean
  sessionCount: number
}

/**
 * Creates a new automation with the same safe defaults as desktop authoring.
 *
 * @param id Stable identifier generated by the caller.
 * @param now Current unix timestamp in seconds.
 * @returns A complete automation ready for the authoring form.
 */
export function createAutomation(id: string, now: number): Automation {
  return {
    id,
    name: '',
    prompt: '',
    agent: {
      provider: 'codex',
      model: null,
      reasoning_effort: null,
      service_tier: null,
      agent_preset: null,
      runtime_mode: 'fullAccess',
      interaction_mode: 'build',
    },
    project_id: null,
    workspace: { kind: 'local' },
    schedule: { kind: 'daily', time: { hour: 9, minute: 0 } },
    overlap: 'skip',
    notification: { enabled: true, trigger: 'onFailure' },
    enabled: true,
    created_at: now,
    updated_at: now,
    last_run_at: null,
    history: [],
  }
}

/**
 * Copies an automation deeply enough for isolated form editing.
 *
 * @param automation Persisted automation to edit.
 * @returns A detached form value.
 */
export function cloneAutomation(automation: Automation): Automation {
  return structuredClone(automation)
}

/**
 * Maps form state to the normalized automation sent in an upsert delta.
 *
 * @param form Current form value.
 * @param now Current unix timestamp in seconds.
 * @returns A trimmed, normalized automation preserving every agent and policy field.
 */
export function automationFromForm(form: Automation, now: number): Automation {
  return {
    ...cloneAutomation(form),
    name: form.name.trim(),
    prompt: form.prompt.trim(),
    agent: {
      ...form.agent,
      model: nullableText(form.agent.model),
      reasoning_effort: nullableText(form.agent.reasoning_effort),
      service_tier: nullableText(form.agent.service_tier),
      agent_preset: nullableText(form.agent.agent_preset),
    },
    schedule: normalizeSchedule(form.schedule),
    updated_at: now,
  }
}

/**
 * Changes schedule frequency while carrying forward the user's time selection.
 *
 * @param schedule Current schedule.
 * @param kind Desired frequency.
 * @returns A valid schedule for the selected frequency.
 */
export function scheduleWithKind(
  schedule: Schedule,
  kind: Schedule['kind'],
): Schedule {
  const time =
    schedule.kind === 'daily' ||
    schedule.kind === 'weekly' ||
    schedule.kind === 'monthly'
      ? schedule.time
      : { hour: 9, minute: schedule.kind === 'hourly' ? schedule.minute : 0 }

  if (kind === 'manual') return { kind: 'manual' }
  if (kind === 'hourly') return { kind: 'hourly', minute: time.minute }
  if (kind === 'daily') return { kind: 'daily', time }
  if (kind === 'weekly') {
    return {
      kind: 'weekly',
      time,
      weekdays:
        schedule.kind === 'weekly' && schedule.weekdays.length
          ? [...schedule.weekdays]
          : ['monday'],
    }
  }
  return {
    kind: 'monthly',
    time,
    days:
      schedule.kind === 'monthly' && schedule.days.length
        ? [...schedule.days]
        : [1],
  }
}

/**
 * Opens deletion confirmation on the non-cascading path and counts exact sessions.
 *
 * @param automationId Automation being removed.
 * @param sessions Current daemon session summaries.
 * @returns Confirmation state with cascade explicitly disabled.
 */
export function createDeleteConfirmation(
  automationId: string,
  sessions: AgentSession[],
): AutomationDeleteConfirmation {
  return {
    automationId,
    cascadeSessions: false,
    sessionCount: sessions.filter(
      (session) => session.originating_automation === automationId,
    ).length,
  }
}

function normalizeSchedule(schedule: Schedule): Schedule {
  if (schedule.kind === 'manual') return schedule
  if (schedule.kind === 'hourly') {
    return { kind: 'hourly', minute: clamp(schedule.minute, 0, 59) }
  }
  const time = {
    hour: clamp(schedule.time.hour, 0, 23),
    minute: clamp(schedule.time.minute, 0, 59),
  }
  if (schedule.kind === 'daily') return { kind: 'daily', time }
  if (schedule.kind === 'weekly') {
    const weekdays = [...new Set(schedule.weekdays)]
    return {
      kind: 'weekly',
      time,
      weekdays: weekdays.length ? weekdays : ['monday'],
    }
  }
  const days = [...new Set(schedule.days.map((day) => clamp(day, 1, 31)))].sort(
    (a, b) => a - b,
  )
  return {
    kind: 'monthly',
    time,
    days: days.length ? days : [1],
  }
}

function nullableText(value: string | null | undefined): string | null {
  return value?.trim() || null
}

function clamp(value: number, minimum: number, maximum: number): number {
  return Math.max(minimum, Math.min(maximum, value))
}
